<%--
/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */
--%>

<%@ include file="/init.jsp" %>

<pre>
Requirements:

1. A Web Content Structure with the StructureKey: MY_STRUCTURE_KEY and a field named Code type string indexed as keyword

2. At least a Web Content Template with the TemplateKey: MY_TEMPLATE_KEY, in which the content will be renderized 

3. Set the next properties to your portal-ext.properties:

	#
	# Set this to true if dynamic data mapping template keys should always be
	# autogenerated.
	#
	dynamic.data.mapping.template.force.autogenerate.key=false

	#
	# Set this to true if dynamic data mapping structure keys should always be
	# autogenerated.
	#
	dynamic.data.mapping.structure.force.autogenerate.key=false
</pre>

<%
String tabs1 = ParamUtil.getString(request, "tabs1", "search1");

PortletURL portletURL = renderResponse.createRenderURL();

portletURL.setParameter("tabs1", tabs1);
%>

<liferay-ui:tabs
	value="<%= tabs1 %>"
	names="search1,view-fields"
	url="<%= portletURL.toString() %>"
>
	<liferay-ui:section>
		<liferay-util:include page="/search1.jsp" servletContext="<%= application %>"/>
	</liferay-ui:section>

	<liferay-ui:section>
		<liferay-util:include page="/view-fields.jsp" servletContext="<%= application %>"/>
	</liferay-ui:section>
</liferay-ui:tabs>